package com.datasaz.ecommerce.mappers;

import com.datasaz.ecommerce.models.request.AddressRequest;
import com.datasaz.ecommerce.models.response.AddressResponse;
import com.datasaz.ecommerce.repositories.entities.Address;
import com.datasaz.ecommerce.repositories.entities.AddressType;
import com.datasaz.ecommerce.repositories.entities.Company;
import com.datasaz.ecommerce.repositories.entities.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static org.junit.jupiter.api.Assertions.*;

class AddressMapperV2Test {

    private AddressMapper addressMapper;
    private AddressRequest request;
    private Address entity;
    private AddressResponse response;

    @BeforeEach
    void setUp() {
        addressMapper = new AddressMapper();

        // Full request with all fields
        request = AddressRequest.builder()
                .name("John Doe")
                .email("john.doe@example.com")
                .phoneNumber("+1-234-567-8900")
                .addressLine1("123 Main Street")
                .addressLine2("Apt 4B")
                .city("New York")
                .state("NY")
                .postalCode("10001")
                .country("USA")
                .reference("Leave at front desk")
                .addressType(AddressType.SHIPPING)
                .isDefault(true)
                .build();

        // Full entity with all fields
        entity = Address.builder()
                .id(1L)
                .name("Jane Smith")
                .email("jane.smith@example.com")
                .phoneNumber("+1-987-654-3210")
                .addressLine1("456 Oak Avenue")
                .addressLine2("Suite 200")
                .city("Los Angeles")
                .state("CA")
                .postalCode("90001")
                .country("USA")
                .reference("Call before delivery")
                .addressType(AddressType.BILLING)
                .isDefault(false)
                .user(User.builder().id(1L).build())
                .company(Company.builder().id(1L).build())
                .version(1L)
                .build();

        // Full response
        response = AddressResponse.builder()
                .id(1L)
                .name("Jane Smith")
                .email("jane.smith@example.com")
                .phoneNumber("+1-987-654-3210")
                .addressLine1("456 Oak Avenue")
                .addressLine2("Suite 200")
                .city("Los Angeles")
                .state("CA")
                .postalCode("90001")
                .country("USA")
                .reference("Call before delivery")
                .addressType(AddressType.BILLING)
                .isDefault(false)
                .userId(1L)
                .companyId(1L)
                .version(1L)
                .build();
    }

    // === toEntity Tests ===

    @Test
    @DisplayName("toEntity - full request maps all fields correctly")
    void toEntity_fullRequest_mapsAllFields() {
        Address result = addressMapper.toEntity(request);

        assertNotNull(result);
        assertEquals("John Doe", result.getName());
        assertEquals("john.doe@example.com", result.getEmail());
        assertEquals("+1-234-567-8900", result.getPhoneNumber());
        assertEquals("123 Main Street", result.getAddressLine1());
        assertEquals("Apt 4B", result.getAddressLine2());
        assertEquals("New York", result.getCity());
        assertEquals("NY", result.getState());
        assertEquals("10001", result.getPostalCode());
        assertEquals("USA", result.getCountry());
        assertEquals("Leave at front desk", result.getReference());
        assertEquals(AddressType.SHIPPING, result.getAddressType());
        assertTrue(result.isDefault());
        assertNull(result.getId()); // Generated by DB
        assertNull(result.getUser());
        assertNull(result.getCompany());
        assertNull(result.getVersion());
    }

    @Test
    @DisplayName("toEntity - null request returns null")
    void toEntity_nullRequest_returnsNull() {
        Address result = addressMapper.toEntity(null);
        assertNull(result);
    }

    @ParameterizedTest
    @DisplayName("toEntity - required fields only")
    @ValueSource(strings = {
            "BILLING", "SHIPPING", "EXPEDITION", "CONTACT"
    })
    void toEntity_requiredFieldsOnly(AddressType type) {
        AddressRequest minimal = AddressRequest.builder()
                .name("Minimal")
                .addressLine1("123 St")
                .city("City")
                .postalCode("12345")
                .country("USA")
                .addressType(type)
                .build();

        Address result = addressMapper.toEntity(minimal);

        assertEquals("Minimal", result.getName());
        assertEquals("123 St", result.getAddressLine1());
        assertEquals("City", result.getCity());
        assertEquals("12345", result.getPostalCode());
        assertEquals("USA", result.getCountry());
        assertEquals(type, result.getAddressType());
        assertFalse(result.isDefault()); // Default false
        assertNull(result.getEmail());
        assertNull(result.getPhoneNumber());
        assertNull(result.getAddressLine2());
        assertNull(result.getState());
        assertNull(result.getReference());
    }

    // === toResponse Tests ===

    @Test
    @DisplayName("toResponse - full entity maps all fields correctly")
    void toResponse_fullEntity_mapsAllFields() {
        AddressResponse result = addressMapper.toResponse(entity);

        assertNotNull(result);
        assertEquals(1L, result.getId());
        assertEquals("Jane Smith", result.getName());
        assertEquals("jane.smith@example.com", result.getEmail());
        assertEquals("+1-987-654-3210", result.getPhoneNumber());
        assertEquals("456 Oak Avenue", result.getAddressLine1());
        assertEquals("Suite 200", result.getAddressLine2());
        assertEquals("Los Angeles", result.getCity());
        assertEquals("CA", result.getState());
        assertEquals("90001", result.getPostalCode());
        assertEquals("USA", result.getCountry());
        assertEquals("Call before delivery", result.getReference());
        assertEquals(AddressType.BILLING, result.getAddressType());
        assertFalse(result.isDefault());
        assertEquals(1L, result.getUserId());
        assertEquals(1L, result.getCompanyId());
        assertEquals(1L, result.getVersion());
    }

    @Test
    @DisplayName("toResponse - null entity returns null")
    void toResponse_nullEntity_returnsNull() {
        AddressResponse result = addressMapper.toResponse(null);
        assertNull(result);
    }

    @Test
    @DisplayName("toResponse - entity without user/company maps null IDs")
    void toResponse_noParent_mapsNullIds() {
        entity.setUser(null);
        entity.setCompany(null);

        AddressResponse result = addressMapper.toResponse(entity);

        assertNull(result.getUserId());
        assertNull(result.getCompanyId());
    }

    @Test
    @DisplayName("toResponse - entity with minimal fields")
    void toResponse_minimalEntity() {
        Address minimal = Address.builder()
                .id(2L)
                .name("Minimal")
                .addressLine1("123 St")
                .city("City")
                .postalCode("12345")
                .country("USA")
                .addressType(AddressType.CONTACT)
                .isDefault(false)
                .build();

        AddressResponse result = addressMapper.toResponse(minimal);

        assertEquals("Minimal", result.getName());
        assertEquals("123 St", result.getAddressLine1());
        assertEquals("City", result.getCity());
        assertEquals("12345", result.getPostalCode());
        assertEquals("USA", result.getCountry());
        assertEquals(AddressType.CONTACT, result.getAddressType());
        assertFalse(result.isDefault());
        assertNull(result.getEmail());
        assertNull(result.getPhoneNumber());
        assertNull(result.getAddressLine2());
        assertNull(result.getState());
        assertNull(result.getReference());
        assertNull(result.getUserId());
        assertNull(result.getCompanyId());
        assertNull(result.getVersion());
    }

    // === updateEntityFromRequest Tests ===

    @Test
    @DisplayName("updateEntityFromRequest - updates all fields")
    void updateEntityFromRequest_updatesAllFields() {
        AddressRequest updateRequest = AddressRequest.builder()
                .name("Updated Name")
                .email("updated@example.com")
                .phoneNumber("+1-999-888-7777")
                .addressLine1("Updated St")
                .addressLine2("Updated Apt")
                .city("Updated City")
                .state("Updated State")
                .postalCode("99999")
                .country("Updated Country")
                .reference("Updated Reference")
                .addressType(AddressType.EXPEDITION)
                .isDefault(true)
                .build();

        addressMapper.updateEntityFromRequest(updateRequest, entity);

        assertEquals("Updated Name", entity.getName());
        assertEquals("updated@example.com", entity.getEmail());
        assertEquals("+1-999-888-7777", entity.getPhoneNumber());
        assertEquals("Updated St", entity.getAddressLine1());
        assertEquals("Updated Apt", entity.getAddressLine2());
        assertEquals("Updated City", entity.getCity());
        assertEquals("Updated State", entity.getState());
        assertEquals("99999", entity.getPostalCode());
        assertEquals("Updated Country", entity.getCountry());
        assertEquals("Updated Reference", entity.getReference());
        assertEquals(AddressType.EXPEDITION, entity.getAddressType());
        assertTrue(entity.isDefault());
    }

    @Test
    @DisplayName("updateEntityFromRequest - null request does nothing")
    void updateEntityFromRequest_nullRequest_doesNothing() {
        Address original = Address.builder()
                .name("Original")
                .addressLine1("Original St")
                .isDefault(false)
                .build();

        addressMapper.updateEntityFromRequest(null, original);

        assertEquals("Original", original.getName());
        assertEquals("Original St", original.getAddressLine1());
        assertFalse(original.isDefault());
    }

    @Test
    @DisplayName("updateEntityFromRequest - null entity does nothing")
    void updateEntityFromRequest_nullEntity_doesNothing() {
        // Should not throw NPE
        addressMapper.updateEntityFromRequest(request, null);
        // No assertions needed - method returns void
    }

    @Test
    @DisplayName("updateEntityFromRequest - partial update skips null fields")
    void updateEntityFromRequest_partialUpdate() {
        AddressRequest partial = AddressRequest.builder()
                .name("New Name")
                .addressLine1(null) // Should not change
                .city("New City")
                .isDefault(true)
                .build();

        entity.setName("Old Name");
        entity.setAddressLine1("Old St");
        entity.setCity("Old City");
        entity.setDefault(false);

        addressMapper.updateEntityFromRequest(partial, entity);

        assertEquals("New Name", entity.getName()); // Updated
        assertEquals("Old St", entity.getAddressLine1()); // Unchanged (null in request)
        assertEquals("New City", entity.getCity()); // Updated
        assertTrue(entity.isDefault()); // Updated
    }

    @Test
    @DisplayName("updateEntityFromRequest - can set optional fields to null")
    void updateEntityFromRequest_setsOptionalToNull() {
        AddressRequest nullify = AddressRequest.builder()
                .addressLine2(null)
                .state(null)
                .reference(null)
                .isDefault(true)
                .build();

        entity.setAddressLine2("Old Apt");
        entity.setState("Old State");
        entity.setReference("Old Ref");

        addressMapper.updateEntityFromRequest(nullify, entity);

        assertNull(entity.getAddressLine2()); // Set to null
        assertNull(entity.getState()); // Set to null
        assertNull(entity.getReference()); // Set to null
        assertTrue(entity.isDefault()); // Updated
    }

    @ParameterizedTest
    @DisplayName("updateEntityFromRequest - handles different address types")
    @ValueSource(strings = {"BILLING", "SHIPPING", "EXPEDITION", "CONTACT"})
    void updateEntityFromRequest_differentTypes(String typeStr) {
        AddressType type = AddressType.valueOf(typeStr);
        AddressRequest typeRequest = AddressRequest.builder()
                .addressType(type)
                .isDefault(true)
                .build();

        entity.setAddressType(AddressType.SHIPPING);
        entity.setDefault(false);

        addressMapper.updateEntityFromRequest(typeRequest, entity);

        assertEquals(type, entity.getAddressType());
        assertTrue(entity.isDefault());
    }

    // === Integration Tests ===

    @Test
    @DisplayName("full cycle - request → entity → response")
    void fullCycle_requestToResponse() {
        // Request → Entity
        Address entity = addressMapper.toEntity(request);
        assertNotNull(entity);
        assertEquals("John Doe", entity.getName());

        // Entity → Response
        AddressResponse response = addressMapper.toResponse(entity);
        assertNotNull(response);
        assertEquals("John Doe", response.getName());
        assertEquals(AddressType.SHIPPING, response.getAddressType());
        assertTrue(response.isDefault());

        // Update and verify
        AddressRequest update = AddressRequest.builder()
                .name("Updated Name")
                .addressType(AddressType.BILLING)
                .isDefault(false)
                .build();

        addressMapper.updateEntityFromRequest(update, entity);
        assertEquals("Updated Name", entity.getName());
        assertEquals(AddressType.BILLING, entity.getAddressType());
        assertFalse(entity.isDefault());
    }
}
